### ISSUE TITLE
Likely the password for UART console access

### ISSUE THREAD

**Issue by doz10us** [DrmnSamoLiu/DrmnSamoLiu.github.io#1]
The password you're looking for [here](https://github.com/DrmnSamoLiu/DrmnSamoLiu.github.io/blob/30c9323d929529143fa37d6e9c63e393f1d7f3f3/firmware.html#L62) should be `slprealtek`.

Steps to find:
1. Download GPL sources for the camera from [TP-Link website](https://www.tp-link.com/us/support/gpl-code/).
2. Unpack and navigate to `camera_slp_realtek_c200/torchlight/product_config/ALL/buildroot.config`, line 450.
3. The line contains `CONFIG_SLP_LOGIN_PASSWORD="slprealtek"`.

Credit goes to user @kubik369 for fetching GPL sources and parsing them.

**Comment by DrmnSamoLiu** [comment]
@doz10us 
Thanks for the detail on how to find the password! I'll put the password into our document in the next update and make sure to credit @kubuki369 and you :)
