### ISSUE TITLE
Support Tapo in go2rtc

### ISSUE THREAD

**Issue by AlexxIT** [DrmnSamoLiu/DrmnSamoLiu.github.io#3]
Hi. Maybe you will be interested. I have added your RTSP bypass login to go2rtc:
https://github.com/AlexxIT/go2rtc#source-rtsp

Also I have added support Tapo protocol with two way audio. And ability send audio files and live streams to Tapo cameras:
https://github.com/AlexxIT/go2rtc#source-tapo
https://github.com/AlexxIT/go2rtc#stream-to-camera
https://github.com/AlexxIT/WebRTC#stream-to-camera

**Comment by DrmnSamoLiu** [comment]
Hi, much thanks for implementing our discoveries in a community project!
But I'll also have to let you know that unfortunately TP-Link seems to have patched this vuln. I can't verify since which version number though, haven't use these cams for a long while :(

**Comment by AlexxIT** [comment]
Thanks. I have Tapo TC60 1080p. They have this bug.
